name: FIA Document Checker
on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  check-documents:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y poppler-utils

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pdf2image requests beautifulsoup4 atproto

      - name: Run FIA document checker
        env:
          BLUESKY_USERNAME: ${{ secrets.BLUESKY_USERNAME }}
          BLUESKY_PASSWORD: ${{ secrets.BLUESKY_PASSWORD }}
        run: python hello.py

      - name: Configure Git
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'

      - name: Commit and push if changed
        run: |
          git add processed_docs.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update processed documents list" && git push)
